package de.niroyt.nnc.enums;

public enum CheckCategory {

	COMBAT_ANGLE,
	COMBAT_REACH,
	
	MOVING_FLY,
	MOVING_NOCLIP,
	MOVING_NOSLOWDOWN,
	MOVING_NOWEB,
	MOVING_PHASE,
	MOVING_SAFEWALK,
	MOVING_WATERWALK,
	MOVING_SPRINT,
	MOVING_STRAFE,
	
	PLAYER_INTERACT,
	PLAYER_CHESTSTEALER,
	PLAYER_FASTBOW,
	PLAYER_FASTBREAK,
	PLAYER_FASTHEAL,
	PLAYER_FASTPLACE,
	PLAYER_FASTUSE,
	PLAYER_GHOSTHAND,
	PLAYER_NOFALL,
	PLAYER_NOSWING,
	PLAYER_REACH,
	PLAYER_ZOOT,
	
	INVENTORY_MOVE,
	INVENTORY_INTERACT,
	INVENTORY_ATTACK,
	
	WORLD_SCAFFOLD,
	WORLD_TOWER,
			
	FALSE_ANGLE,
	
	FALSE_PACKETS,
	MORE_PACKETS,
	PACKETS_PING_SPOOF,
	
	INVALID_VELOCITY,
	
	KILLAURA_WALLHACK,
	KILLAURA,
	
	SPEED_JUMP,
	SPEED_GROUND,
	SPEED_WATER
}
